---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: maildev-web
  namespace: apic
spec:
  virtualhost:
    fqdn: maildev-apic.demo01.mea-presales.org
  routes:
  - conditions:
    - prefix: /
    services:
    - name: maildev
      port: 1080
