apiVersion: devportal.apiconnect.ibm.com/v1beta1
kind: DevPortalCluster
metadata:
  name: devportal
  namespace: apic
spec:
  version: 12.1.0.1
  profile: n1xc2.m4
  imagePullSecrets:
  - harbor-registry-secret
  imageRegistry: harbor.adp.example.com/apic
  devportalAdminEndpoint:
    ingressClassName: contour
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: admin-devportal-apic.k8s.adp.example.com
      secretName: devportal-admin-endpoint
  devportalUIEndpoint:
    ingressClassName: contour
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: devportal-apic.k8s.adp.example.com
      secretName: devportal-ui-endpoint
  analyticsRef:
    name: analytics
    namespace: apic
  adminClientSubjectDN: CN=devportal-admin-client,O=cert-manager
  microServiceSecurity: certManager
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  encryptionSecret:
    secretName: devportal-enc-key
  isStandalone: false
  license:
    accept: true
    use: nonproduction
    metric: PROCESSOR_VALUE_UNIT
    license: L-PDZK-TWDH97
