#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# NOTE: Only one type of rotation operation can be performed at a time. You must choose either:
 
# 1. Certificate Rotation Only
apiVersion: analytics.apiconnect.ibm.com/v1beta1
kind: AnalyticsSecretRotation
metadata:
  name: analytics-rotate-secret
spec:
  # Name of the analytics cluster's secrets you want to rotate
  analyticsCluster: analytics
  
  # Certificate rotation - use this to rotate TLS certificates
  rotateCertificates:
    certificates:
    - analytics-ca  
    - analytics-admin  
  
  # Internal credential rotation - must be false when rotating certificates
  rotateInternalCredentials: false 

# 2. Internal Credential Rotation Only
apiVersion: analytics.apiconnect.ibm.com/v1beta1
kind: AnalyticsSecretRotation
metadata:
  name: analytics-rotate-secret
spec:
  # Name of the analytics cluster's secrets you want to rotate
  analyticsCluster: analytics
  
  # No certificate rotation specified
  
  # Internal credential rotation - use this to rotate Opensearch user/password credentials
  rotateInternalCredentials: true
