---
# Analytics Ingestion Endpoint
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: analytics-ai-endpoint
  namespace: NAMESPACE_PLACEHOLDER
spec:
  virtualhost:
    fqdn: ai.DNS_PLACEHOLDER
    tls:
      secretName: analytics-ai-endpoint
  routes:
  - services:
    - name: analytics-mtls-gw
      port: 4443
      protocol: tls
      validation:
        caSecret: analytics-ca
        subjectName: analytics-mtls-gw.NAMESPACE_PLACEHOLDER.svc.cluster.local
