apiVersion: v1
kind: Pod
metadata:
  name: busybox-clear-pvc
  namespace: NAMESPACE_PLACEHOLDER
spec:
  containers:
  - name: busybox
    image: REGISTRY_PLACEHOLDER/busybox:1.37
    command:
    - sh
    - -c
    - |
      echo "Starting PVC cleanup..."
      echo "Clearing /data PVC..."
      rm -rf /data/* /data/.* 2>/dev/null || true
      echo "/data cleared"
      echo "Clearing /wal PVC..."
      rm -rf /wal/* /wal/.* 2>/dev/null || true
      echo "/wal cleared"
      echo "PVC cleanup completed successfully"
      sleep 3600
    volumeMounts:
    - name: data
      mountPath: /data
    - name: wal
      mountPath: /wal
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: PVC_DATA_PLACEHOLDER
  - name: wal
    persistentVolumeClaim:
      claimName: PVC_WAL_PLACEHOLDER
  imagePullSecrets:
  - name: REGISTRY_SECRET_PLACEHOLDER
  restartPolicy: Never
