apiVersion: gateway.apiconnect.ibm.com/v1beta1
kind: GatewayCluster
metadata:
  name: ai-gateway
  namespace: apic
spec:
  version: 12.1.0.1
  profile: n1xc4.m8
  imagePullSecrets:
  - harbor-registry-secret
  imageRegistry: harbor.adp.example.com/apic
  apicGatewayServiceV5CompatibilityMode: false
  gatewayEndpoint:
    ingressClassName: contour
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: ai-rgw-apic.k8s.adp.example.com
      secretName: ai-gateway-endpoint
  gatewayManagerEndpoint:
    ingressClassName: contour
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: ai-rgwd-apic.k8s.adp.example.com
      secretName: ai-gateway-manager-endpoint
  apicGatewayServiceTLS:
    secretName: ai-gateway-service
  apicGatewayPeeringTLS:
    secretName: ai-gateway-peering
  mgmtPlatformEndpointCASecret:
    secretName: management-ca
  datapowerLogLevel: 3
  license:
    accept: true
    use: nonproduction
    license: L-SBZZ-CNR329
  tokenManagementService:
    enabled: true
    storage:
      storageClassName: nfs-ssd
      volumeSize: 30Gi
  adminUser:
    secretName: datapower-admin-credentials
  mtlsValidateClient: false
