---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mailhog-web
  namespace: apic
spec:
  virtualhost:
    fqdn: mailhog-apic.talos-pc.zebra-cloud.net
  routes:
  - conditions:
    - prefix: /
    services:
    - name: mailhog
      port: 8025
